##############################################################################
#                                                                            #
#                                                                            #
##############################################################################

[meta]
TITLE           = Hello
DESCRIPTION     = Hello World for Contexo.

[general]
NAME            = Hello

[libraries]
hello      = bare_hello

[exports]
PUBLIC_HEADERS  = helloworld.h
