; generated by ARM C/C++ Compiler, RVCT4.0 [Build 400]
; commandline armcc [--asm compute_answer.c]
        ARM
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

compute_answer PROC
        MOV      r0,#0x2a
        BX       lr
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT compute_answer [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {FALSE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
