; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	C:\svn\contexo\examples\hello_view\hello_modules\hello\src\compute_answer.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_compute_answer
; Function compile flags: /Odtp
_TEXT	SEGMENT
_compute_answer PROC
; File c:\svn\contexo\examples\hello_view\hello_modules\hello\src\compute_answer.c
; Line 2
	push	ebp
	mov	ebp, esp
; Line 3
	mov	eax, 42					; 0000002aH
; Line 4
	pop	ebp
	ret	0
_compute_answer ENDP
_TEXT	ENDS
END
